Apbetween
jgrapht/jgrapht pull request #1017
Opened 2020-12-16 11:53 UTC by d-michail

This PR contains the implementation of #1016 and additionally an implementation of Betweenness Centrality using arbitrary precision arithmetic (using the Apfloat library). 

Since the Apfloat library is licensed under the LGPL while we are using both LGPL+EPL, we cannot merge this immediately. We have contacted the author and he is willing to either relicense the Apfloat library with a permissive license (MIT, Apache, BSD, etc.) or to dual-license. 

Thus, this PR needs to wait for a new release of Apfloat with a compatible library. If this does not happen, we can always reimplement the functionality using BigDecimal. An implementation with BigDecimal would be correct, but much slower. 

 ----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

2021-01-01 10:13 UTC, jsichi requested changes
Marking this one as request changes so it doesn't get accidentally merged before the license issue is resolved.

2021-11-05 08:51 UTC, d-michail commented
@jsichi The license problem should now be resolved.

2021-11-08 12:53 UTC, jsichi commented
Hurray!

2021-11-08 12:54 UTC, jsichi approved these changes

2021-11-08 12:54 UTC, merged