Restore Deque Interface in DoublyLinkedList
jgrapht/jgrapht pull request #1169
Opened 2023-12-25 06:58 UTC by syoon2

_Resolves #1154_

This PR:
- Restores `java.util.Deque` interface in `DoublyLinkedList`, i.e., reverts #1159
- Implements `DoublyLinkedList.reversed()`, as specified in [`java.util.SequencedCollection`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/SequencedCollection.html) in Java 21 API. This includes:
  - Generifying data types of `ListNodeImpl` to `ListNode`
  - Adding `ListNode.getList()` method
  - Adding anonymous inner class to provide reversed view (isolating this to a separate class should be straightforward though)
  - Adding `DoublyLinkedList.head()` (as counterpart of `DoublyLinkedList.tail()`)
  - Changing visibility of `DoublyLinkedList.tail()` to package private (originally private)
  - Adding a wrapper `ReversedListNode` class

The reversed view returned by `DoublyLinkedList.reversed()`, as implemented by this PR, is unmodifiable. This is to avoid headaches with data inconsistencies, although making the modifications "write through" to the original list should be doable.

Note that this PR's goal is compatibility across versions.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ ] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
  _Probably after #1163 gets merged (I really don't want to write JUnit 4 tests when I know the change is just around the corner) - and why this PR is a draft for now_
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

2023-12-25 07:13 UTC, syoon2 commented
cc @d-michail @jkinable

2023-12-27 06:38 UTC, syoon2 commented
Range-diff
```text
-:  -------- > 1:  e625da93 JUnit 5 Migration (#1163)
-:  -------- > 2:  9c98ae8a Credits for last merge.
1:  029ceda2 = 3:  6dd593ea Restore deque interface
2:  7518565f = 4:  f47fc719 Implement DoublyLinkedList.reversed()
3:  32e42eba = 5:  e1f41a3a Move anonymous inner class to ReversedDoublyLinkedList class
4:  73e2dc44 = 6:  d8d0b186 Block inverts in the reversed view
```

2024-01-03 00:52 UTC, syoon2 commented
Range-diff
```text
-:  -------- > 1:  e8c9ddb4 CI Maintenance (#1167)
-:  -------- > 2:  97e2a63b Credits for last merge.
-:  -------- > 3:  cbaa12b8 Remove npm caching (#1171)
1:  6dd593ea = 4:  52bf5c17 Restore deque interface
2:  f47fc719 = 5:  0a1b665f Implement DoublyLinkedList.reversed()
3:  e1f41a3a = 6:  03f3ddaf Move anonymous inner class to ReversedDoublyLinkedList class
4:  d8d0b186 = 7:  ae7353af Block inverts in the reversed view
```

2024-01-04 04:56 UTC, jsichi commented
@d-michail or @jkinable if you get a chance, please take a look, otherwise I will.

2024-01-06 02:13 UTC, syoon2 commented
Range-diff
```text
 -:  ---------- >  1:  c84f505943 Bump org.apache.maven.plugins:maven-source-plugin from 3.2.1 to 3.3.0 (#1172)
 -:  ---------- >  2:  d7b88a059f Bump org.apache.maven.plugins:maven-release-plugin from 3.0.0 to 3.0.1 (#1173)
 -:  ---------- >  3:  e7375cced7 Bump com.puppycrawl.tools:checkstyle from 10.9.2 to 10.12.7 (#1174)
 -:  ---------- >  4:  ba55f0c372 Bump antlr4.version from 4.13.0 to 4.13.1 (#1175)
 -:  ---------- >  5:  02c65beb8e Bump jmh.version from 1.36 to 1.37 (#1176)
 -:  ---------- >  6:  28eb0e085f Bump org.apache.maven.plugins:maven-gpg-plugin from 3.0.1 to 3.1.0 (#1177)
 -:  ---------- >  7:  644a438692 Javadoc Maintenance (#1168)
 -:  ---------- >  8:  6ca09060bf Credits for last merge.
 -:  ---------- >  9:  d322517bcc Javadoc Maintenance: Cleanup (#1179)
 -:  ---------- > 10:  381a595783 Manually export performance test packages (#1178)
 -:  ---------- > 11:  eaa76bc9a3 Fix incorrect symbol replacement (#1180)
 1:  52bf5c171e = 12:  5d9dac1bac Restore deque interface
 2:  0a1b665ff3 = 13:  f3eed67c16 Implement DoublyLinkedList.reversed()
 3:  03f3ddaf5c = 14:  1eca5fc9a0 Move anonymous inner class to ReversedDoublyLinkedList class
 4:  ae7353afac = 15:  1dda141979 Block inverts in the reversed view
 5:  1f6280791d = 16:  7e205c1be0 Make iterators from reversed view unmodifiable
 6:  c54a388ff8 = 17:  bd50929faa Block node modification operations
 7:  d61e228259 = 18:  6293706d1b Add basic tests for reversed view
 8:  4e0ddeb4ce = 19:  16653722ac Make iterator impl work with reversed view
 9:  9dd501b767 = 20:  4c23f3a632 Remove redundant override
10:  3334a86c46 = 21:  caf3e01b10 Add more iterator tests
11:  700b98f7a6 = 22:  5bde8247b2 Avoid using size variable for iterator creation
12:  fe1f75357f <  -:  ---------- Manually export org.jgrapht.util for testing
13:  86415d5536 = 23:  dbef82e9a8 Fix incorrect test design
14:  17a4eeb978 ! 24:  7f1ef211c4 Make Surefire happier with test discovery
    @@ Metadata
      ## Commit message ##
         Make Surefire happier with test discovery

    - ## jgrapht-core/pom.xml ##
    -@@
    -                         <configuration>
    -                             <argLine>
    -                                 --add-exports org.jgrapht.core/org.jgrapht.interfaces=ALL-UNNAMED
    --                                --add-exports org.jgrapht.core/org.jgrapht.util=ALL-UNNAMED
    -                             </argLine>
    -                             <excludes>
    -                                 <exclude>**/perf/**</exclude>
    -@@
    -                 <configuration>
    -                     <argLine>
    -                         --add-exports org.jgrapht.core/org.jgrapht.interfaces=ALL-UNNAMED
    --                        --add-exports org.jgrapht.core/org.jgrapht.util=ALL-UNNAMED
    -                     </argLine>
    -                     <excludedGroups>optional</excludedGroups>
    -                     <groups>slow</groups>
    -
      ## jgrapht-core/src/test/java/org/jgrapht/util/DoublyLinkedListTest.java ##
     @@ jgrapht-core/src/test/java/org/jgrapht/util/DoublyLinkedListTest.java: public class DoublyLinkedListTest
           */
15:  4e02a73397 <  -:  ---------- pom formatting
```

2024-01-15 04:14 UTC, jsichi commented
Any way to get rid of all the ListNodeImpl typecasts, perhaps by introducing a common ancestor for DoublyLinkedList and ReverseDoublyLinkedListView?  ListNode would then be associated with the common ancestor, while ListNodeImpl would be associated only with DoublyLinkedList.

2024-01-25 00:21 UTC, syoon2 commented
> Any way to get rid of all the ListNodeImpl typecasts, perhaps by introducing a common ancestor for DoublyLinkedList and ReverseDoublyLinkedListView?

I think there would be ways to remove the typecasts (and I agree doing so), but I doubt whether introducing another ancestor for `DoublyLinkedList` and its view would be the "right way" to achieve the goal. Unfortunately, I have other commitments that prevent me from getting back to this PR, so it could take a while for me to follow up.

2024-03-13 16:05 UTC, jsichi commented
If it's too much trouble, I'll merge as is, since this is an internal implementation detail.

2024-03-14 01:48 UTC, syoon2 commented on jgrapht-core/src/main/java/org/jgrapht/util/DoublyLinkedList.java
> +            ((AbstractListNode<E>) node).setList(this);
The cleanest way I can think of to remove that cast is making `ListNode` an abstract class (i.e., deleting the current `ListNode` interface and renaming `AbstractListNode` to `ListNode`), which I am hesitating to do so for many different reasons. WDYT?

2024-03-14 05:56 UTC, jsichi commented on jgrapht-core/src/main/java/org/jgrapht/util/DoublyLinkedList.java
> +            ((AbstractListNode<E>) node).setList(this);
Actually I think https://github.com/jgrapht/jgrapht/commit/f4ec977d12c82b82acec0a60402d0a7bdcc8564a would be fine.  Exposing the nodes at all, as we were doing before this PR, is already breaking encapuslation, and I don't think the distinction between interface and abstract class is meaningful here.

2024-03-21 05:10 UTC, jsichi requested changes
Looking good!  One last change request.  Can you add a test that assigns a list instance to a variable of type Deque, confirming the high-level intention of the change?

2024-03-21 08:05 UTC, syoon2 commented
> Can you add a test that assigns a list instance to a variable of type Deque, confirming the high-level intention of the change?

I think that asserting `instanceof` makes a more straightforward test case and added 55f5296 in. Let me know if you want the following code snippet running explicitly tested:
```java
DoublyLinkedList<?> list = new DoublyLinkedList<>();
Deque<?> deque = list;
```

2024-03-21 12:17 UTC, jsichi approved these changes
Good as is!

2024-03-21 12:17 UTC, merged